### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by quanhao129611** [ucl-bug/jwave#225]
Hello, I encountered the same problem when installing jwave as when installing holab:
(testholab) omnisky@omnisky:~$ python
Python 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import jwave
Traceback (most recent call last):
   File "<stdin>", line 1, in <module>
   File "/home/omnisky/anaconda3/envs/testholab/lib/python3.10/site-packages/jwave/__init__.py", line 19, in <module>
     from jwave import acoustics as ac
   File "/home/omnisky/anaconda3/envs/testholab/lib/python3.10/site-packages/jwave/acoustics/__init__.py", line 17, in <module>
     from .operators import *
   File "/home/omnisky/anaconda3/envs/testholab/lib/python3.10/site-packages/jwave/acoustics/operators.py", line 23, in <module>
     from jwave.geometry import Medium
   File "/home/omnisky/anaconda3/envs/testholab/lib/python3.10/site-packages/jwave/geometry.py", line 26, in <module>
     from plum import parametric, type_of
ImportError: cannot import name 'type_of' from 'plum' (/home/omnisky/anaconda3/envs/testholab/lib/python3.10/site-packages/plum/__init__.py)

**Desktop (please complete the following information):**
 - OS: [Ubuntu]
 - Version [16.04]

**Comment by astanziola** [comment]
Yes, I think I have messed up things when updating to the new plum. Will fix now, sorry for that!

**Comment by astanziola** [comment]
This should be fixed in the latest release, but please let me know if you find any problem (feel free to reopen in case!), and sorry again for all the trouble!
